spring.application.name=payroll-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

